#+title: Bob Dylan 歌词收藏

** A Hard Rain’s A-Gonna Fall
#+BEGIN_VERSE
Oh, where have you been, my blue-eyed son?
Oh, where have you been, my darling young one?
I've stumbled on the side of twelve misty mountains
I've walked and I've crawled on six crooked highways
I've stepped in the middle of seven sad forests
I've been out in front of a dozen dead oceans
I've been ten thousand miles in the mouth of a graveyard
And it's a hard, and it's a hard, it's a hard, and it's a hard
And it's a hard rain's a-gonna fall

Oh, what did you see, my blue-eyed son?
Oh, what did you see, my darling young one?
I saw a newborn baby with wild wolves all around it
I saw a highway of diamonds with nobody on it
I saw a black branch with blood that kept drippin'
I saw a room full of men with their hammers a-bleedin'
I saw a white ladder all covered with water
I saw ten thousand talkers whose tongues were all broken
I saw guns and sharp swords in the hands of young children
And it's a hard, and it's a hard, it's a hard, it's a hard
And it's a hard rain's a-gonna fall

And what did you hear, my blue-eyed son?
And what did you hear, my darling young one?
I heard the sound of a thunder, it roared out a warnin'
Heard the roar of a wave that could drown the whole world
Heard one hundred drummers whose hands were a-blazin’
Heard ten thousand whisperin’ and nobody listenin’
Heard one person starve, I heard many people laughin'
Heard the song of a poet who died in the gutter
Heard the sound of a clown who cried in the alley
And it's a hard, and it's a hard, it's a hard, it's a hard
And it's a hard rain's a-gonna fall

Oh, who did you meet, my blue-eyed son?
Who did you meet, my darling young one?
I met a young child beside a dead pony
I met a white man who walked a black dog
I met a young woman whose body was burning
I met a young girl, she gave me a rainbow
I met one man who was wounded in love
I met another man who was wounded with hatred
And it's a hard, it's a hard, it's a hard, it's a hard
It's a hard rain's a-gonna fall

Oh, what'll you do now, my blue-eyed son?
Oh, what'll you do now, my darling young one?
I'm a-goin' back out 'fore the rain starts a-fallin'
I'll walk to the depths of the deepest black forest
Where the people are many and their hands are all empty
Where the pellets of poison are flooding their waters
Where the home in the valley meets the damp dirty prison
Where the executioner's face is always well-hidden
Where hunger is ugly, where souls are forgotten
Where black is the color, where none is the number
And I'll tell it and think it and speak it and breathe it
And reflect it from the mountain so all souls can see it
Then I'll stand on the ocean until I start sinkin'
But I'll know my song well before I start singin'
And it's a hard, it's a hard, it's a hard, it's a hard
It's a hard rain's a-gonna fall
#+END_VERSE

** Mr Tambourine Man
#+BEGIN_VERSE
Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

Though I know that evening's empire has returned into sand
Vanished from my hand
Left me blindly here to stand but still not sleeping
My weariness amazes me, I'm branded on my feet
I have no one to meet
And the ancient empty street's too dead for dreaming

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

Take me on a trip upon your magic swirling ship
My senses have been stripped
My hands can't feel to grip
My toes too numb to step
Wait only for my boot heels to be wandering
I'm ready to go anywhere, I'm ready for to fade
Into my own parade
Cast your dancing spell my way, I promise to go under it

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

Though you might hear laughing, spinning, swinging madly across the sun
It's not aimed at anyone
It's just escaping on the run
And but for the sky there are no fences facing
And if you hear vague traces of skipping reels of rhyme
To your tambourine in time
It's just a ragged clown behind
I wouldn't pay it any mind
It's just a shadow you're seeing that he's chasing

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

And take me disappearing through the smoke rings of my mind
Down the foggy ruins of time
Far past the frozen leaves
The haunted frightened trees
Out to the windy beach
Far from the twisted reach of crazy sorrow
Yes, to dance beneath the diamond sky
With one hand waving free
Silhouetted by the sea
Circled by the circus sands
With all memory and fate
Driven deep beneath the waves
Let me forget about today until tomorrow

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you
#+END_VERSE

** Desolation Row
#+BEGIN_VERSE
They’re selling postcards of the hanging
They’re painting the passports brown
The beauty parlor is filled with sailors
The circus is in town
Here comes the blind commissioner
They’ve got him in a trance
One hand is tied to the tight-rope walker
The other is in his pants
And the riot squad they’re restless
They need somewhere to go
As Lady and I look out tonight
From Desolation Row

Cinderella, she seems so easy
“It takes one to know one,” she smiles
And puts her hands in her back pockets
Bette Davis style
And in comes Romeo, he’s moaning
“You Belong to Me I Believe”
And someone says, “You’re in the wrong place my friend
You better leave”
And the only sound that’s left
After the ambulances go
Is Cinderella sweeping up
On Desolation Row

Now the moon is almost hidden
The stars are beginning to hide
The fortune-telling lady
Has even taken all her things inside
All except for Cain and Abel
And the hunchback of Notre Dame
Everybody is making love
Or else expecting rain
And the Good Samaritan, he’s dressing
He’s getting ready for the show
He’s going to the carnival tonight
On Desolation Row

Now Ophelia, she’s ’neath the window
For her I feel so afraid
On her twenty-second birthday
She already is an old maid
To her, death is quite romantic
She wears an iron vest
Her profession’s her religion
Her sin is her lifelessness
And though her eyes are fixed upon
Noah’s great rainbow
She spends her time peeking
Into Desolation Row

Einstein, disguised as Robin Hood
With his memories in a trunk
Passed this way an hour ago
With his friend, a jealous monk
He looked so immaculately frightful
As he bummed a cigarette
Then he went off sniffing drainpipes
And reciting the alphabet
Now you would not think to look at him
But he was famous long ago
For playing the electric violin
On Desolation Row

Dr. Filth, he keeps his world
Inside of a leather cup
But all his sexless patients
They’re trying to blow it up
Now his nurse, some local loser
She’s in charge of the cyanide hole
And she also keeps the cards that read
“Have Mercy on His Soul”
They all play on pennywhistles
You can hear them blow
If you lean your head out far enough
From Desolation Row

Across the street they’ve nailed the curtains
They’re getting ready for the feast
The Phantom of the Opera
A perfect image of a priest
They’re spoonfeeding Casanova
To get him to feel more assured
Then they’ll kill him with self-confidence
After poisoning him with words
And the Phantom’s shouting to skinny girls
“Get Outa Here If You Don’t Know
Casanova is just being punished for going
To Desolation Row”

Now at midnight all the agents
And the superhuman crew
Come out and round up everyone
That knows more than they do
Then they bring them to the factory
Where the heart-attack machine
Is strapped across their shoulders
And then the kerosene
Is brought down from the castles
By insurance men who go
Check to see that nobody is escaping
To Desolation Row

Praise be to Nero’s Neptune
The Titanic sails at dawn
And everybody’s shouting
“Which Side Are You On?”
And Ezra Pound and T. S. Eliot
Fighting in the captain’s tower
While calypso singers laugh at them
And fishermen hold flowers
Between the windows of the sea
Where lovely mermaids flow
And nobody has to think too much
About Desolation Row

Yes, I received your letter yesterday
(About the time the doorknob broke)
When you asked how I was doing
Was that some kind of joke?
All these people that you mention
Yes, I know them, they’re quite lame
I had to rearrange their faces
And give them all another name
Right now I can’t read too good
Don’t send me no more letters, no
Not unless you mail them
From Desolation Row
#+END_VERSE
