#+title: 厉害的CEO是什么样的？

我不想成为CEO，但是万老师在这篇文章里面给的几点关于出色的CEO的特质，值得每个人学习。对于现在这个状态的我，尤其需要学会最后一点：给人“可靠感”。

如果我没有记错的话，第一点是快速决断的能力。

找到人支持你的决策

#+BEGIN_QUOTE
有位CEO，每当重大决定的时候，都会画一个人物关系图，图中标出了办成这件事情需要涉及到的所有重要人员。然后他会和这些人挨个谈话，取得他们对这个决定的支持。如果有人始终反对他的决定，那么他就会尽力把这个反对的力量往正面的方向引导。

如果别人不支持你，你的“政令”就出不了办公室。所以好的CEO一定要能够将自己的理念传达给董事会以及员工，取得众人的理解和支持，让别人和你站在同一条战线上。这也是为什么CEO要经常向高层汇报工作，有什么成绩得经常说，用成绩证明自己确实值得信任。
#+END_QUOTE

从长远角度出发思考问题和制定策略

#+BEGIN_QUOTE
当市场环境快速变化的时候， CEO应该积极领着公司做出相应的改变，比如推出新产品、公司转型等等，这是CEO最重要的职责之一。

想要做到这一点，CEO必须能够从长远考虑问题。我们可以把公司所有问题分为三类：短期，中期和长远 —— 那么这个研究发现，不行的CEO会花30%的时间去考虑长远问题，而厉害的CEO会花50%的时间去考虑长远问题。这就是说，CEO应该把大部分时间用在考虑公司的长期战略上，而不应该把太多精力花在日常公司管理和运营方面。

如果你心里有一个非常明确的长期战略，你看问题的眼光就不一样了。从战略视角去看，你会获得见微知著的能力！你会从自己的社交圈里，从各个地方取得信息，大大提高敏感度。可能别人没觉得这个事有多重要，可是你一眼就能发现其中可能蕴含着市场即将发生的重大变化！这样你就会抢先一步对公司做出相应的调整。
#+END_QUOTE


给人“可靠感”

#+BEGIN_QUOTE
想要当一个受人肯定的CEO，你必须给人一种“可靠感”。这有两层意思。

第一，你得给人一个合理的预期。这也就是说你计划要干什么事，公司业绩在几个月或者一年内能达到什么程度，你要提前告诉股东和员工，让人觉得你“有谱”。

第二，到了时候，你得达到、最好能超出这个预期，让人觉得你“靠谱”。我觉得这个文化有点受到财务报表制度的影响。上市公司每个季度都要发布一次财报，你得总结这个季度做到了什么，还得汇报下季度想做到什么。华尔街对报表非常敏感，给每个公司一个预期，一旦达不到预期，股价就会受到惩罚。
这是一个非常束缚人的文化，CEO必须时刻确保公司业绩达到预期。在这种情况下，一个发挥稳定、每次都能让公司业绩比华尔街预期稍微好一点的CEO，就非常可贵了
#+END_QUOTE
